# Generated by Django 2.1.3 on 2018-12-06 08:09

from django.db import migrations, models
import university.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('logo_url', models.ImageField(blank=True, null=True, upload_to=university.models.upload_logo_image)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
