# Generated by Django 2.1.4 on 2018-12-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityschools',
            name='is_main_school',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
