# Generated by Django 2.1.3 on 2018-12-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
