# Generated by Django 2.1.4 on 2018-12-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20181211_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityschools',
            name='is_main_school',
            field=models.BooleanField(default=False),
        ),
    ]
