# Generated by Django 2.1.4 on 2018-12-06 10:06

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20181206_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
