# Generated by Django 2.1.4 on 2018-12-06 10:26

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20181206_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
    ]
