# Generated by Django 2.1.4 on 2018-12-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('university', '0004_auto_20181206_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='school',
            field=models.ManyToManyField(to='school.School'),
        ),
    ]
