# Generated by Django 2.1.4 on 2018-12-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_university_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='school',
            new_name='schools',
        ),
    ]
