# Generated by Django 2.1.4 on 2018-12-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_type',
            field=models.CharField(blank=True, choices=[('UNV', 'University'), ('SCH', 'School')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
